# Regenerates inst/AUTHORS.
#
# CRAN requires that "the authorship and copyright information for the Rust code
# must be included in the DESCRIPTION file. That includes any Rust sources
# included as dependencies" (Using Rust in CRAN packages). With ~140 vendored
# crates that cannot go in DESCRIPTION literally, so DESCRIPTION carries a
# Copyright field pointing here, and this file carries the detail.
#
# Generated from `cargo metadata`, which is authoritative for each crate's
# declared license and authors. Many modern crates omit `authors` entirely (it
# became optional), so the crate name, version, license and repository stand as
# the attribution where no author is declared.
#
# Run after any dependency change: Rscript data-raw/make-authors.R

meta <- jsonlite::fromJSON(
  system2("cargo",
          c("metadata", "--format-version", "1", "--offline",
            "--manifest-path", "src/rust/Cargo.toml"),
          stdout = TRUE),
  simplifyVector = FALSE
)

pkgs <- meta$packages
# Drop our own wrapper crate: it is covered by the package's own DESCRIPTION.
pkgs <- Filter(function(p) !is.null(p$source), pkgs)
pkgs <- pkgs[order(tolower(vapply(pkgs, function(p) p$name, character(1))))]

entry <- function(p) {
  authors <- unlist(p$authors)
  authors <- authors[nzchar(authors)]
  license <- if (!is.null(p$license)) p$license else
    if (!is.null(p$license_file)) paste0("see ", p$license_file) else "unspecified"

  lines <- sprintf("%s %s (%s)", p$name, p$version, license)
  if (length(authors)) {
    lines <- c(lines, paste0("  ", authors))
  } else if (!is.null(p$repository)) {
    # No declared authors: the upstream repository is the attribution.
    lines <- c(lines, paste0("  ", p$repository))
  }
  lines
}

header <- c(
  "Authors and copyright holders of the vendored Rust crates",
  "=========================================================",
  "",
  "This package links a Rust static library built from the crates listed below.",
  "Their sources are not shipped in this tarball; they are downloaded at build",
  "time as a verified archive (see tools/vendor.R). Each crate is listed with",
  "the license and authors it declares in its own Cargo.toml. Where a crate",
  "declares no authors, its upstream repository is given instead.",
  "",
  sprintf("Generated by data-raw/make-authors.R on %s from cargo metadata.",
          format(Sys.Date())),
  sprintf("Crates: %d", length(pkgs)),
  ""
)

dir.create("inst", showWarnings = FALSE)
writeLines(c(header, unlist(lapply(pkgs, entry))), "inst/AUTHORS")

cat("Wrote inst/AUTHORS:", length(pkgs), "crates,",
    length(readLines("inst/AUTHORS")), "lines,",
    file.size("inst/AUTHORS"), "bytes\n")

# Licenses present, so the DESCRIPTION License field can be checked against them.
licenses <- sort(table(vapply(pkgs, function(p)
  if (!is.null(p$license)) p$license else "unspecified", character(1))),
  decreasing = TRUE)
cat("\nDeclared licenses across the tree:\n")
print(licenses)
